### ISSUE TITLE
AREPL print output is in variable-width font

### ISSUE THREAD

**Issue by LightCC** [Almenon/AREPL-vscode#277]
The print output is not in a fixed-width font, but the variable output appears to be. Is this expected behavior?

I would prefer both the print and variable output to be fixed width. Is this something I can change with settings, or would it be a code change?

It may be possible with #257 : Setting font size, though I'm not sure the steps to implement that.

Thanks!!

**Comment by Almenon** [comment]
Sorry about that, the print output should have been fixed width. I realized it was a problem a while ago (see https://github.com/Almenon/AREPL-vscode/issues/218) but it was blocked by a vscode bug and I never ended up getting back to it. I've updated the code so that arepl uses the font specified by the editor.fontFamil setting. (which I believe vscode sets to monospaced fonts by default)

I'll keep this issue open until I release the new code.

In the meantime you can use the custom css setting by using the following css:

`#print{font-family:var(--vscode-editor-font-family)}`

You can alter the above css as you wish. If you want to reference the arepl stylesheet to see how I use css for arepl you can find it [here](https://github.com/Almenon/AREPL-vscode/blob/master/media/pythonPreview.css).

**Comment by Almenon** [comment]
I just released v1.0.18 - look better?

**Comment by Almenon** [comment]
No response - closing, hopefully this helped @LightCC out. If not let me know :)
