### ISSUE TITLE
automatically use right python version

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-vscode#299]
AREPL takes the python extension python path setting. The problem is the user might only define that setting for a specific folder/workspace, so if arepl is done elsewhere it won't have that path and perhaps try to use `py` on windows which might point to python 2.

Also I've noticed recently that windows has python linked to python 2 .... not sure what's up with that, whether it's my machine or whether a recent windows update added python 2 for some reason.

**Comment by jsolly** [comment]
I ran into an issue with VSC on mac where AREPL was warning me that it did not work with Python 2. I was quite confused because VSC had Python 3 set as the default interpreter.
![image](https://user-images.githubusercontent.com/9572232/75293093-4debaf80-57da-11ea-8330-19f91250000e.png)

I went into the settings of CSV and found that Python.pythonPath was set to 'python' 
![image](https://user-images.githubusercontent.com/9572232/75293244-ac189280-57da-11ea-9435-58b20402087b.png)

I changed it to 'python3' and then everything was working with AREPL

**Comment by malikoth** [comment]
Just stumbled on AREPL today, looks really neat, thanks for making it!

This issue I think is a pretty big stumbling block for my use, though.  Each of my projects has a `Pipfile` in it with its own virtualenv.  So in order for AREPL to be useful in the context of the applications I'm developing, it needs access to the packages installed in each of those virtualenvs.  It really needs to be able to use the interpreter defined and set in VSC, since I can't be going into the settings and modifying the python path each time I switch projects.

And for what it's worth, I think there's a difference between the Python extension's python path setting, and the workspace's defined interpreter, which you can set via the command palette or the status bar at the bottom (as seen in @jsolly 's first screenshot, where it says, "Python 3.7.5 64-bit".  I think AREPL should use the workspace interpreter, rather than pulling the python path from ANY of the settings locations.

**Comment by Almenon** [comment]
@malikoth welcome!

> since I can't be going into the settings and modifying the python path each time I switch projects.

You don't need to do that. Instead of setting pythonpath on a user level, across all projects, I suggest in your case setting it on a project/folder level. You can set arepl.pythonpath or python.pythonpath in the workspace or folder settings for your project and each time you load the project after that it should use one of those settings. 

I should also note that arepl.pythonpath accepts paths relative to the root of the repo and accepts environment variables. For example, if you have a environment variable x=fah and a path `${env:x}\foo` the resulting path arepl uses would be `C:\path_to_workspace\fah\foo`. This functionality mirrors the functionality available in the python extension: https://code.visualstudio.com/docs/python/environments

Hopefully this info is helpful to you. I'm not sure I understand your situation properly.
In the meantime I'll look into this :)

**Comment by Almenon** [comment]
Update to my above comment: I forgot that the `python.pythonpath` defined at the **folder level** *does not work* with arepl. Unfortunately there appears to be a bug with vscode where it returns the workspace setting instead of the folder setting, so the folder setting is not used 😬. Python.pythonpath updates the folder level setting making this especially problematic.

See #300

**Comment by Almenon** [comment]
> Indeed, I realized that a few minutes after adding my comment here. I believe I did set the AREPL pythonpath on a folder level, and it worked just fine.

👍 

> This is sadly, not useful to me. I'm using pipenv for managing my environments, and it creates virtualenvs that (by default) do not reside in the repository folder at all. If my project directory is sandbox, the path to python for this project might be /Users/malikoth/.venvs/sandbox-MjeucXBr/bin/python.

I see, thanks for the information. That reminds me of pyenv, pyenv+virtualenv does kinda the same thing.

> I don't know how you would access the environment interpreter settings, but if there is a way to pull that data from the python plugin if it's available, I still think it would make AREPL easier to get into. :) 

AREPL has been doing this already. AREPL automatically uses python.pythonPath setting if arepl.pythonPath is not set. This used to work correctly, but something changed and caused it to stop working properly (or maybe I just didn't notice the bug till now?). I opened a issue with vscode - see https://github.com/microsoft/vscode/issues/94241 - and they gave me a fix so hopefully I can fix it for the next update :)

> Incidentally, I already removed AREPL again because the command to run a block of code (Cmd-Enter) was overriding the default command for creating a new line below. In retrospect, it wouldn't have been that hard to just change the default binding for running a block of code in AREPL. I'll have to go install it again!

Oh, interesting. I had a hard time deciding what command to choose for that. There's no perfect choice because so many short commands are already used by vscode or some pre existing extension. If I may ask, why do you do cmd-enter instead of enter?

**Comment by Almenon** [comment]
I just added the fix and tested it and it appears to be working :D

**Comment by malikoth** [comment]
> Why do you do cmd-enter instead of enter?

Because VSCode automatically inserts a closing quotation mark when I enter the initial quotation mark to start typing a string literal, and a closing square bracket, curly brace, or paren when I type the corresponding opener.  Often I'll finish typing the important part of a line, and there are 2-3 or more characters left to the right of my cursor still.  I can type those characters manually, even though I can see that they're already there (in which case, VSCode knows that it inserted those characters automatically, and so if I type them manually, it doesn't insert a new one, it essentially just moves my cursor one character to the right), or I can hit Cmd-Right to go to the end of the string and then press enter, or I can press Cmd-Enter to insert a new line below and go directly to it.  Also same reasoning if I'm editing some value in the middle of  the line.

**Comment by Almenon** [comment]
@malikoth The newest version of arepl (v1.0.23) should correctly use the python extension interpreter setting if arepl.pythonpath is not set - can you let me know if it is working once you update please?

**Comment by malikoth** [comment]
Works great for me.  (Sorry for delay! Life and stuff!)  Excited to have AREPL installed again and use it for prototyping and stuff.  :)  I'm not the original poster of this issue, but I personally would consider this issue resolved.

**Comment by Almenon** [comment]
Sweet :)
