### ISSUE TITLE
Can't close AREPL when infinite looping

### ISSUE THREAD

**Issue by ThePhoenixCoding** [Almenon/AREPL-vscode#318]
**Describe the bug**
When AREPL already executes a loop which is infinite at the time of execution, it can't be stopped anymore until restarting VSCode

**To Reproduce**
1. Start AREPL
2. Type
i = 1
while i < 10:
                  print(i)"
// AREPL starts executing
3. Add "i+=1" to loop

**Expected behavior**
After adding the new code which would make the loop ending, AREPL refreshes and prints the values 1 to 10

**Other Information (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.8.2 64-bit

**Additional context**
This issue also affects other extensions which fail to work as AREPL is apparently blocking them or not leaving ressources while looping infinitely

**Comment by Almenon** [comment]
You don't need to restart vscode.

Previously when this happened I just closed arepl by closing the arepl tab on the right, fixed the loop, and restarted it. Bam, done.

Unfortunately the behavior appears to have gotten worse now that I disabled buffering.
Now when I restart arepl it takes a long time to restart and when it finally does restart it still shows the print output from the last run instead of the landing page. The print output goes away when I fix the loop, not sure how that got left over.

I think the reason why it's freezing up is because it's getting spammed with print output from python. I launch python in unbuffered mode because otherwise print output doesn't arrive until the end of the run*. Python then flushes every single print call, which is great if you have a few prints so you can see it in real time. Less great when you have a infinite loop that overwhelms the extension 😬 .

\* Unless you print so much that the buffer gets filled up, in which case it flushes. If you're printing a single sentence this will take very roughly 300 iterations to fill up (the buffer is 8KB).

I could overwrite the print method with a custom one that flushes every X milliseconds. I was planning on overwriting the print method anyways to be able to get line numbers from the print. 

In the meantime as a workaround you can disable unbuffered mode.

`    "AREPL.pythonOptions": []`

If you need real-time prints you can use flush=True when calling print.

And of course the other workaround is to just not write infinite loops :P

**Comment by TheBassTeddy** [comment]
Oh, you’re right. It does actually stop and restart after some time!

 

Thanks a lot for your explanatory reply! 😊

 

Von: Almenon <notifications@github.com> 
Gesendet: Samstag, 28. März 2020 20:22
An: Almenon/AREPL-vscode <AREPL-vscode@noreply.github.com>
Cc: TheBassTeddy <alexa.gnoss@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [Almenon/AREPL-vscode] Can't close AREPL when infinite looping (#318)

 

You don't need to restart vscode.

Previously when this happened I just closed arepl by closing the arepl tab on the right, fixed the loop, and restarted it. Bam, done.

Unfortunately the behavior appears to have gotten worse now that I disabled buffering.
Now when I restart arepl it takes a long time to restart and when it finally does restart it still shows the print output from the last run instead of the landing page. The print output goes away when I fix the loop, not sure how that got left over.

I think the reason why it's freezing up is because it's getting spammed with print output from python. I launch python in unbuffered mode because otherwise print output doesn't arrive until the end of the run*. Python then flushes every single print call, which is great if you have a few prints so you can see it in real time. Less great when you have a infinite loop that overwhelms the extension 😬 .

* Unless you print so much that the buffer gets filled up, in which case it flushes. If you're printing a single sentence this will take very roughly 300 iterations to fill up (the buffer is 8KB).

I could overwrite the print method with a custom one that flushes every X milliseconds. I was planning on overwriting the print method anyways to be able to get line numbers from the print.

In the meantime as a workaround you can disable unbuffered mode.

"AREPL.pythonOptions": []

If you need real-time prints you can use flush=True when calling print.

And of course the other workaround is to just not write infinite loops :P

**Comment by Almenon** [comment]
Restarting performs better now. Possibly because of https://github.com/Almenon/AREPL-vscode/pull/332
