### ISSUE TITLE
command 'extension.evalPythonInRealTime' not found

### ISSUE THREAD

**Issue by yukepeter** [Almenon/AREPL-vscode#81]
command 'extension.evalPythonInRealTime' not found
I recently encounter this problem when reopen my vscode and trying to pull up arepl. Does anyone know how can I get over it? Thanks in advance!

**Comment by Almenon** [comment]
Dang, that's not good.  What OS do you have?  If you try activating the extension and go to help -> developer tools, do you see any logs?

**Comment by Almenon** [comment]
Also do you get the same error after restarting VSCode?

**Comment by yukepeter** [comment]
I am using Mac OS,Darwin Kernel Version 16.7.0 . In the developer tool console, there is an error says, extensionService.ts:892 Activating extension 'almenon.arepl' failed: EISDIR: illegal operation on a directory, mkdir '/'.

**Comment by Almenon** [comment]
ah, okay.  What happened is that there was an error when trying to add the arepldump library to your path - I do it by adding an arepldump.pth file to your user-sites directory, and if that directory does not exist I try to create it.  But in your case something went wrong when trying to create it ... 😞

To avoid the error you can create the folder yourself.  If you execute 
```
python3 -m site --user-site
```

in the command line what output do you get?

**Comment by yukepeter** [comment]
In my case it is /Users/keyu/Library/Python/3.6/lib/python/site-packages

**Comment by Almenon** [comment]
okay - try making that folder manually and your problem should go away.

**Comment by Almenon** [comment]
Meanwhile I'm going to try running AREPL on my ubuntu VM and see if I get the same error

**Comment by Almenon** [comment]
alright.  AREPL worked in my ubuntu VM, so not sure why it is failling on your linux box.  My dad has a linux machine at home so next time I go over to his house I can test it there.

**Comment by yukepeter** [comment]
I am using macOS Sierra 10.12.6

**Comment by yukepeter** [comment]
I create the directory manually by using mkdir -p /Users/keyu/Library/Python/3.6/lib/python/site-packages with the help of my friend Ollie and the problem is solved now! Thanks.

**Comment by Almenon** [comment]
welcome :)

**Comment by Almenon** [comment]
Reopening - I've confirmed this is a problem on mac and windows when the user does not have any python  user packages installed.  I'll be fixing it soon.

**Comment by Almenon** [comment]
The fix for mac was very simple:

```python
if(curDir == '/') return '/' // to avoid EISDIR error on mac
```

The fix should *theoretically* also work on ubuntu, but I'll wait till tomorrow when I have a ubuntu VM to test with before releasing the fix.

For the windows fix I used an [updated version](http://rextester.com/XZI35837) of mkDirByPathSync I found in the comments of the [stackoverflow answer](https://stackoverflow.com/questions/31645738/how-to-create-full-path-with-nodes-fs-mkdirsync).

The script works by splitting up the path into sections and trying to create the directories starting at the first section.  So it would try to create C:\\, and then fail due to EPERM.  The author fixed it by only allowing a permission error to fail if it happens when creating the last directory.
